global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'slo', 'service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h
  receiver: 'pagerduty-oncall'
  routes:
    - match:
        severity: page
      receiver: 'pagerduty-oncall'
    - match:
        severity: warning
      receiver: 'slack-notifications'

receivers:
  - name: 'pagerduty-oncall'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        client: 'Nester Alertmanager'
        client_url: 'https://grafana.nester.fi'
        details:
          firing: '{{ len .Alerts.Firing }}'

  - name: 'opsgenie-oncall'
    opsgenie_configs:
      - api_key: '${OPSGENIE_API_KEY}'
        priority: 'P1'

  - name: 'slack-notifications'
    webhook_configs:
      - url: 'http://localhost:5001/'
